"""Sample patients for the Lone Star Clinic.

Everything here is fictional. Emails use example.com and phone numbers use the
555-01xx range reserved for fiction. `last_visit_days_ago` is relative to the
day the database is seeded, so the data never looks stale.
"""

from typing import Any

# Hand-written patients: the regulars.
PATIENTS: list[dict[str, Any]] = [
    {
        "first_name": "Slim",
        "last_name": "Calhoun",
        "date_of_birth": "1958-03-14",
        "phone": "830-555-0101",
        "address_line": "412 Hill Country Rd",
        "city": "Luckenbach",
        "postal_code": "78624",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["Hypertension", "Type 2 diabetes"],
        "allergies": ["Penicillin"],
        "last_visit_days_ago": 6,
    },
    {
        "first_name": "Lefty",
        "last_name": "McGraw",
        "date_of_birth": "1971-11-02",
        "phone": "830-555-0102",
        "address_line": "88 Cypress St",
        "city": "Bandera",
        "postal_code": "78003",
        "blood_type": "A+",
        "status": "active",
        "conditions": ["Rotator cuff tendinopathy (left shoulder)"],
        "allergies": [],
        "last_visit_days_ago": 19,
    },
    {
        "first_name": "Tex",
        "last_name": "Holloway",
        "date_of_birth": "1949-07-04",
        "phone": "806-555-0103",
        "address_line": "1701 Route 66",
        "city": "Amarillo",
        "postal_code": "79101",
        "blood_type": "B+",
        "status": "critical",
        "conditions": ["COPD", "Atrial fibrillation"],
        "allergies": ["Sulfa drugs"],
        "last_visit_days_ago": 2,
    },
    {
        "first_name": "Dusty",
        "last_name": "Ramirez",
        "date_of_birth": "1985-05-21",
        "phone": "432-555-0104",
        "address_line": "9 Mystery Lights Ln",
        "city": "Marfa",
        "postal_code": "79843",
        "blood_type": "O-",
        "status": "active",
        "conditions": ["Asthma", "Seasonal allergic rhinitis (cedar fever)"],
        "allergies": ["Mountain cedar pollen", "Dust mites"],
        "last_visit_days_ago": 31,
    },
    {
        "first_name": "Annie",
        "last_name": "Whitfield",
        "date_of_birth": "1990-08-13",
        "phone": "830-555-0105",
        "address_line": "230 Peach Orchard Rd",
        "city": "Fredericksburg",
        "postal_code": "78624",
        "blood_type": "AB+",
        "status": "active",
        "conditions": [],
        "allergies": ["Latex"],
        "last_visit_days_ago": 143,
    },
    {
        "first_name": "Hoss",
        "last_name": "Dalton",
        "date_of_birth": "1966-01-30",
        "phone": "806-555-0106",
        "address_line": "5400 Cotton Gin Rd",
        "city": "Lubbock",
        "postal_code": "79401",
        "blood_type": "A-",
        "status": "inactive",
        "conditions": ["Obstructive sleep apnea", "Hyperlipidemia"],
        "allergies": [],
        "last_visit_days_ago": 412,
    },
    {
        "first_name": "Belle",
        "last_name": "Navarro",
        "date_of_birth": "1978-12-09",
        "phone": "830-555-0107",
        "address_line": "17 Dance Hall Row",
        "city": "Gruene",
        "postal_code": "78130",
        "blood_type": "B-",
        "status": "active",
        "conditions": ["Migraine without aura"],
        "allergies": ["Codeine"],
        "last_visit_days_ago": 24,
    },
    {
        "first_name": "Wyatt",
        "last_name": "Mercer",
        "date_of_birth": "1994-04-17",
        "phone": "512-555-0108",
        "address_line": "300 Mercer St",
        "city": "Dripping Springs",
        "postal_code": "78620",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["ACL reconstruction (right knee), 2023"],
        "allergies": [],
        "last_visit_days_ago": 58,
    },
    {
        "first_name": "Clementine",
        "last_name": "Hayes",
        "date_of_birth": "1936-10-25",
        "phone": "325-555-0109",
        "address_line": "62 Pecan Grove",
        "city": "Abilene",
        "postal_code": "79601",
        "blood_type": "A+",
        "status": "critical",
        "conditions": ["Congestive heart failure", "Chronic kidney disease (stage 3)"],
        "allergies": ["Iodinated contrast"],
        "last_visit_days_ago": 1,
    },
    {
        "first_name": "Rusty",
        "last_name": "Callahan",
        "date_of_birth": "1982-06-06",
        "phone": "512-555-0110",
        "address_line": "208 Smokehouse Ave",
        "city": "Lockhart",
        "postal_code": "78644",
        "blood_type": "AB-",
        "status": "active",
        "conditions": ["Gastroesophageal reflux disease"],
        "allergies": ["Shellfish"],
        "last_visit_days_ago": 77,
    },
    {
        "first_name": "Pearl",
        "last_name": "Whitlock",
        "date_of_birth": "1955-02-18",
        "phone": "325-555-0111",
        "address_line": "14 Concho River Dr",
        "city": "San Angelo",
        "postal_code": "76901",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["Osteoarthritis (both knees)", "Hypothyroidism"],
        "allergies": [],
        "last_visit_days_ago": 12,
    },
    {
        "first_name": "Shorty",
        "last_name": "Baines",
        "date_of_birth": "1969-09-09",
        "phone": "432-555-0112",
        "address_line": "1 Ghost Town Rd",
        "city": "Terlingua",
        "postal_code": "79852",
        "blood_type": "B+",
        "status": "inactive",
        "conditions": ["Gout"],
        "allergies": ["Aspirin"],
        "last_visit_days_ago": 520,
    },
    {
        "first_name": "Maverick",
        "last_name": "Stone",
        "date_of_birth": "2001-03-03",
        "phone": "512-555-0113",
        "address_line": "2100 Barton Springs Rd",
        "city": "Austin",
        "postal_code": "78704",
        "blood_type": "A+",
        "status": "active",
        "conditions": [],
        "allergies": [],
        "last_visit_days_ago": 95,
    },
    {
        "first_name": "Daisy",
        "last_name": "Longmire",
        "date_of_birth": "2014-07-22",
        "phone": "512-555-0114",
        "address_line": "77 Blue Hole Ln",
        "city": "Wimberley",
        "postal_code": "78676",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["Asthma (mild intermittent)"],
        "allergies": ["Peanuts"],
        "last_visit_days_ago": 40,
    },
    {
        "first_name": "Cody",
        "last_name": "Brazos",
        "date_of_birth": "1988-11-11",
        "phone": "254-555-0115",
        "address_line": "615 Suspension Bridge Way",
        "city": "Waco",
        "postal_code": "76701",
        "blood_type": "A-",
        "status": "active",
        "conditions": ["Lumbar strain"],
        "allergies": [],
        "last_visit_days_ago": 9,
    },
    {
        "first_name": "Jolene",
        "last_name": "Pruitt",
        "date_of_birth": "1975-04-28",
        "phone": "936-555-0116",
        "address_line": "33 Piney Woods Ct",
        "city": "Nacogdoches",
        "postal_code": "75961",
        "blood_type": "B+",
        "status": "active",
        "conditions": ["Type 2 diabetes", "Generalized anxiety disorder"],
        "allergies": ["Lisinopril (cough)"],
        "last_visit_days_ago": 15,
    },
    {
        "first_name": "Hondo",
        "last_name": "Vega",
        "date_of_birth": "1962-08-08",
        "phone": "956-555-0117",
        "address_line": "940 Rio Grande Blvd",
        "city": "Laredo",
        "postal_code": "78040",
        "blood_type": "O-",
        "status": "critical",
        "conditions": ["Coronary artery disease (stent placed 2025)", "Hypertension"],
        "allergies": [],
        "last_visit_days_ago": 3,
    },
    {
        "first_name": "Sadie",
        "last_name": "Hollis",
        "date_of_birth": "1998-01-19",
        "phone": "830-555-0118",
        "address_line": "51 Granite Shoals Dr",
        "city": "Marble Falls",
        "postal_code": "78654",
        "blood_type": "AB+",
        "status": "active",
        "conditions": ["Iron-deficiency anemia"],
        "allergies": [],
        "last_visit_days_ago": 66,
    },
    {
        "first_name": "Gus",
        "last_name": "Abernathy",
        "date_of_birth": "1944-05-05",
        "phone": "830-555-0119",
        "address_line": "7 Guadalupe Bend",
        "city": "Kerrville",
        "postal_code": "78028",
        "blood_type": "A+",
        "status": "inactive",
        "conditions": ["Sensorineural hearing loss", "Benign prostatic hyperplasia"],
        "allergies": [],
        "last_visit_days_ago": 388,
    },
    {
        "first_name": "Loretta",
        "last_name": "Pickett",
        "date_of_birth": "1959-12-01",
        "phone": "512-555-0120",
        "address_line": "1200 Chisholm Trail",
        "city": "Round Rock",
        "postal_code": "78681",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["Osteoporosis"],
        "allergies": ["Sulfa drugs"],
        "last_visit_days_ago": 28,
    },
    {
        "first_name": "Bo",
        "last_name": "Tanner",
        "date_of_birth": "2009-09-15",
        "phone": "512-555-0121",
        "address_line": "402 Lost Pines Rd",
        "city": "Bastrop",
        "postal_code": "78602",
        "blood_type": "B-",
        "status": "active",
        "conditions": ["Concussion (junior rodeo), resolved"],
        "allergies": [],
        "last_visit_days_ago": 110,
    },
    {
        "first_name": "Doc",
        "last_name": "Sutherland",
        "date_of_birth": "1951-06-20",
        "phone": "432-555-0122",
        "address_line": "19 Big Bend Hwy",
        "city": "Alpine",
        "postal_code": "79830",
        "blood_type": "A+",
        "status": "active",
        "conditions": ["Hypertension"],
        "allergies": ["Bee and wasp venom"],
        "last_visit_days_ago": 47,
    },
    {
        "first_name": "Ruby",
        "last_name": "Montoya",
        "date_of_birth": "1983-02-14",
        "phone": "915-555-0123",
        "address_line": "860 Franklin Mountain Dr",
        "city": "El Paso",
        "postal_code": "79901",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["Gestational diabetes (2019), resolved"],
        "allergies": ["Amoxicillin"],
        "last_visit_days_ago": 201,
    },
    {
        "first_name": "Smokey",
        "last_name": "Jarrett",
        "date_of_birth": "1973-10-31",
        "phone": "361-555-0124",
        "address_line": "5 Fishing Pier Rd",
        "city": "Port Aransas",
        "postal_code": "78373",
        "blood_type": "AB+",
        "status": "inactive",
        "conditions": ["Chronic bronchitis", "Tobacco use disorder"],
        "allergies": [],
        "last_visit_days_ago": 455,
    },
]

# Pools for the generated patients. 10 first names x 10 last names gives 100
# unique people; see `generated_patient` in seed.py for how they are combined.
FIRST_NAMES = [
    "Buck", "Hank", "Jesse", "Wade", "Colt",
    "Reba", "Dolly", "Patsy", "Tammy", "June",
]  # fmt: skip
LAST_NAMES = [
    "Abbott", "Boone", "Crockett", "Driscoll", "Espinoza",
    "Fuentes", "Garrison", "Hutchins", "Ibarra", "Jennings",
]  # fmt: skip
TOWNS = [
    ("Austin", "78701"), ("San Antonio", "78205"), ("Fort Worth", "76102"),
    ("Galveston", "77550"), ("Corpus Christi", "78401"), ("Tyler", "75702"),
    ("Midland", "79701"), ("Del Rio", "78840"), ("Uvalde", "78801"),
    ("Brenham", "77833"), ("Shiner", "77984"),
]  # fmt: skip
CONDITIONS = [
    "Hypertension", "Type 2 diabetes", "Hyperlipidemia", "Asthma", "Osteoarthritis",
    "Hypothyroidism", "Chronic low back pain", "Gastroesophageal reflux disease",
    "Migraine", "Seasonal allergic rhinitis (cedar fever)",
]  # fmt: skip
ALLERGIES = ["Penicillin", "Sulfa drugs", "Latex", "Shellfish", "Peanuts", "Aspirin"]
BLOOD_TYPES = ["O+", "A+", "B+", "O-", "A-", "AB+", "B-", "AB-"]
