"""Sample patients for the Lone Star Clinic.

Everything here is fictional. Emails use example.com and phone numbers use the
555-01xx range reserved for fiction. `last_visit_days_ago` is relative to the
day the database is seeded, so the data never looks stale. Clinical notes are
`(days_ago, text)` pairs, relative in the same way.
"""

from typing import Any

# Hand-written patients: the regulars.
PATIENTS: list[dict[str, Any]] = [
    {
        "first_name": "Slim",
        "last_name": "Calhoun",
        "date_of_birth": "1958-03-14",
        "phone": "830-555-0101",
        "address_line": "412 Hill Country Rd",
        "city": "Luckenbach",
        "postal_code": "78624",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["Hypertension", "Type 2 diabetes"],
        "medications": ["Lisinopril 10 mg daily", "Metformin 500 mg twice daily"],
        "allergies": ["Penicillin"],
        "last_visit_days_ago": 6,
        "notes": [
            (
                190,
                "Annual physical. BP 148/92. Talked about cutting back on brisket and salt. Started lisinopril 10 mg daily.",
            ),
            (
                95,
                "BP 138/86 on lisinopril. A1c 7.4%. Reinforced diet changes and referred to diabetes education.",
            ),
            (
                6,
                "A1c down to 6.9% and BP 132/82. Reports walking the fence line every morning. Continue current plan; recheck in three months.",
            ),
        ],
    },
    {
        "first_name": "Lefty",
        "last_name": "McGraw",
        "date_of_birth": "1971-11-02",
        "phone": "830-555-0102",
        "address_line": "88 Cypress St",
        "city": "Bandera",
        "postal_code": "78003",
        "blood_type": "A+",
        "status": "active",
        "conditions": ["Rotator cuff tendinopathy (left shoulder)"],
        "medications": ["Naproxen 500 mg as needed"],
        "allergies": [],
        "last_visit_days_ago": 19,
        "notes": [
            (
                60,
                "Left shoulder pain after a week of roping practice. Painful arc on abduction. Rotator cuff tendinopathy suspected; started physical therapy and naproxen.",
            ),
            (
                19,
                "Shoulder improving with physical therapy; range of motion nearly full. Cleared for light ranch work, no roping for four more weeks.",
            ),
        ],
    },
    {
        "first_name": "Tex",
        "last_name": "Holloway",
        "date_of_birth": "1949-07-04",
        "phone": "806-555-0103",
        "address_line": "1701 Route 66",
        "city": "Amarillo",
        "postal_code": "79101",
        "blood_type": "B+",
        "status": "critical",
        "conditions": ["COPD", "Atrial fibrillation"],
        "medications": [
            "Tiotropium inhaler daily",
            "Metoprolol 50 mg twice daily",
            "Apixaban 5 mg twice daily",
        ],
        "allergies": ["Sulfa drugs"],
        "last_visit_days_ago": 2,
        "notes": [
            (
                30,
                "More short of breath over two weeks. SpO2 91% on room air. Prednisone burst started and inhaler technique reviewed.",
            ),
            (
                9,
                "Palpitations. ECG shows atrial fibrillation, rate 112. Metoprolol increased; anticoagulation continued.",
            ),
            (
                2,
                "COPD flare not fully settled. Arranged a home oxygen assessment. Follow up in one week, sooner if breathing worsens.",
            ),
        ],
    },
    {
        "first_name": "Dusty",
        "last_name": "Ramirez",
        "date_of_birth": "1985-05-21",
        "phone": "432-555-0104",
        "address_line": "9 Mystery Lights Ln",
        "city": "Marfa",
        "postal_code": "79843",
        "blood_type": "O-",
        "status": "active",
        "conditions": ["Asthma", "Seasonal allergic rhinitis (cedar fever)"],
        "medications": [
            "Fluticasone inhaler twice daily",
            "Albuterol inhaler as needed",
            "Cetirizine 10 mg daily",
        ],
        "allergies": ["Mountain cedar pollen", "Dust mites"],
        "last_visit_days_ago": 31,
        "notes": [
            (
                31,
                "Cedar fever flare with wheeze. Peak flow 78% of personal best. Stepped up inhaled steroid and advised keeping windows shut on high-pollen days.",
            ),
        ],
    },
    {
        "first_name": "Annie",
        "last_name": "Whitfield",
        "date_of_birth": "1990-08-13",
        "phone": "830-555-0105",
        "address_line": "230 Peach Orchard Rd",
        "city": "Fredericksburg",
        "postal_code": "78624",
        "blood_type": "AB+",
        "status": "active",
        "conditions": [],
        "medications": [],
        "allergies": ["Latex"],
        "last_visit_days_ago": 143,
    },
    {
        "first_name": "Hoss",
        "last_name": "Dalton",
        "date_of_birth": "1966-01-30",
        "phone": "806-555-0106",
        "address_line": "5400 Cotton Gin Rd",
        "city": "Lubbock",
        "postal_code": "79401",
        "blood_type": "A-",
        "status": "inactive",
        "conditions": ["Obstructive sleep apnea", "Hyperlipidemia"],
        "medications": ["Atorvastatin 20 mg nightly"],
        "allergies": [],
        "last_visit_days_ago": 412,
    },
    {
        "first_name": "Belle",
        "last_name": "Navarro",
        "date_of_birth": "1978-12-09",
        "phone": "830-555-0107",
        "address_line": "17 Dance Hall Row",
        "city": "Gruene",
        "postal_code": "78130",
        "blood_type": "B-",
        "status": "active",
        "conditions": ["Migraine without aura"],
        "medications": ["Sumatriptan 50 mg as needed"],
        "allergies": ["Codeine"],
        "last_visit_days_ago": 24,
    },
    {
        "first_name": "Wyatt",
        "last_name": "Mercer",
        "date_of_birth": "1994-04-17",
        "phone": "512-555-0108",
        "address_line": "300 Mercer St",
        "city": "Dripping Springs",
        "postal_code": "78620",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["ACL reconstruction (right knee), 2023"],
        "medications": [],
        "allergies": [],
        "last_visit_days_ago": 58,
    },
    {
        "first_name": "Clementine",
        "last_name": "Hayes",
        "date_of_birth": "1936-10-25",
        "phone": "325-555-0109",
        "address_line": "62 Pecan Grove",
        "city": "Abilene",
        "postal_code": "79601",
        "blood_type": "A+",
        "status": "critical",
        "conditions": ["Congestive heart failure", "Chronic kidney disease (stage 3)"],
        "medications": ["Furosemide 40 mg twice daily", "Carvedilol 6.25 mg twice daily"],
        "allergies": ["Iodinated contrast"],
        "last_visit_days_ago": 1,
        "notes": [
            (
                14,
                "Weight up 2 kg in a week with ankle swelling. Furosemide increased to 40 mg twice daily. Low-salt diet reviewed with her daughter.",
            ),
            (
                1,
                "Weight back to baseline and swelling resolved. Creatinine stable at 1.4. Continue current diuretic dose; recheck labs in two weeks.",
            ),
        ],
    },
    {
        "first_name": "Rusty",
        "last_name": "Callahan",
        "date_of_birth": "1982-06-06",
        "phone": "512-555-0110",
        "address_line": "208 Smokehouse Ave",
        "city": "Lockhart",
        "postal_code": "78644",
        "blood_type": "AB-",
        "status": "active",
        "conditions": ["Gastroesophageal reflux disease"],
        "medications": ["Omeprazole 20 mg daily"],
        "allergies": ["Shellfish"],
        "last_visit_days_ago": 77,
    },
    {
        "first_name": "Pearl",
        "last_name": "Whitlock",
        "date_of_birth": "1955-02-18",
        "phone": "325-555-0111",
        "address_line": "14 Concho River Dr",
        "city": "San Angelo",
        "postal_code": "76901",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["Osteoarthritis (both knees)", "Hypothyroidism"],
        "medications": ["Levothyroxine 75 mcg daily", "Acetaminophen 500 mg as needed"],
        "allergies": [],
        "last_visit_days_ago": 12,
    },
    {
        "first_name": "Shorty",
        "last_name": "Baines",
        "date_of_birth": "1969-09-09",
        "phone": "432-555-0112",
        "address_line": "1 Ghost Town Rd",
        "city": "Terlingua",
        "postal_code": "79852",
        "blood_type": "B+",
        "status": "inactive",
        "conditions": ["Gout"],
        "medications": ["Allopurinol 100 mg daily"],
        "allergies": ["Aspirin"],
        "last_visit_days_ago": 520,
    },
    {
        "first_name": "Maverick",
        "last_name": "Stone",
        "date_of_birth": "2001-03-03",
        "phone": "512-555-0113",
        "address_line": "2100 Barton Springs Rd",
        "city": "Austin",
        "postal_code": "78704",
        "blood_type": "A+",
        "status": "active",
        "conditions": [],
        "medications": [],
        "allergies": [],
        "last_visit_days_ago": 95,
    },
    {
        "first_name": "Daisy",
        "last_name": "Longmire",
        "date_of_birth": "2014-07-22",
        "phone": "512-555-0114",
        "address_line": "77 Blue Hole Ln",
        "city": "Wimberley",
        "postal_code": "78676",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["Asthma (mild intermittent)"],
        "medications": ["Albuterol inhaler as needed", "Epinephrine auto-injector as needed"],
        "allergies": ["Peanuts"],
        "last_visit_days_ago": 40,
        "notes": [
            (
                40,
                "Well-child visit. Asthma well controlled, rescue inhaler used less than once a month. School action plan updated. Carries epinephrine for peanut allergy.",
            ),
        ],
    },
    {
        "first_name": "Cody",
        "last_name": "Brazos",
        "date_of_birth": "1988-11-11",
        "phone": "254-555-0115",
        "address_line": "615 Suspension Bridge Way",
        "city": "Waco",
        "postal_code": "76701",
        "blood_type": "A-",
        "status": "active",
        "conditions": ["Lumbar strain"],
        "medications": ["Ibuprofen 400 mg as needed"],
        "allergies": [],
        "last_visit_days_ago": 9,
        "notes": [
            (
                9,
                "Low back strain after loading hay bales. No red flags on exam. Advised heat, gentle stretching and a short course of ibuprofen.",
            ),
        ],
    },
    {
        "first_name": "Jolene",
        "last_name": "Pruitt",
        "date_of_birth": "1975-04-28",
        "phone": "936-555-0116",
        "address_line": "33 Piney Woods Ct",
        "city": "Nacogdoches",
        "postal_code": "75961",
        "blood_type": "B+",
        "status": "active",
        "conditions": ["Type 2 diabetes", "Generalized anxiety disorder"],
        "medications": ["Metformin 1000 mg twice daily", "Sertraline 50 mg daily"],
        "allergies": ["Lisinopril (cough)"],
        "last_visit_days_ago": 15,
    },
    {
        "first_name": "Hondo",
        "last_name": "Vega",
        "date_of_birth": "1962-08-08",
        "phone": "956-555-0117",
        "address_line": "940 Rio Grande Blvd",
        "city": "Laredo",
        "postal_code": "78040",
        "blood_type": "O-",
        "status": "critical",
        "conditions": ["Coronary artery disease (stent placed 2025)", "Hypertension"],
        "medications": [
            "Aspirin 81 mg daily",
            "Clopidogrel 75 mg daily",
            "Atorvastatin 80 mg nightly",
        ],
        "allergies": [],
        "last_visit_days_ago": 3,
        "notes": [
            (
                45,
                "Six-month check after stent placement. No chest pain on exertion. Taking aspirin, clopidogrel and atorvastatin as prescribed.",
            ),
            (
                3,
                "Chest tightness while mending fence, eased with rest. ECG unchanged. Urgent cardiology review arranged; told to call 911 if pain returns at rest.",
            ),
        ],
    },
    {
        "first_name": "Sadie",
        "last_name": "Hollis",
        "date_of_birth": "1998-01-19",
        "phone": "830-555-0118",
        "address_line": "51 Granite Shoals Dr",
        "city": "Marble Falls",
        "postal_code": "78654",
        "blood_type": "AB+",
        "status": "active",
        "conditions": ["Iron-deficiency anemia"],
        "medications": ["Ferrous sulfate 325 mg daily"],
        "allergies": [],
        "last_visit_days_ago": 66,
    },
    {
        "first_name": "Gus",
        "last_name": "Abernathy",
        "date_of_birth": "1944-05-05",
        "phone": "830-555-0119",
        "address_line": "7 Guadalupe Bend",
        "city": "Kerrville",
        "postal_code": "78028",
        "blood_type": "A+",
        "status": "inactive",
        "conditions": ["Sensorineural hearing loss", "Benign prostatic hyperplasia"],
        "medications": ["Tamsulosin 0.4 mg nightly"],
        "allergies": [],
        "last_visit_days_ago": 388,
    },
    {
        "first_name": "Loretta",
        "last_name": "Pickett",
        "date_of_birth": "1959-12-01",
        "phone": "512-555-0120",
        "address_line": "1200 Chisholm Trail",
        "city": "Round Rock",
        "postal_code": "78681",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["Osteoporosis"],
        "medications": ["Alendronate 70 mg weekly", "Calcium with vitamin D daily"],
        "allergies": ["Sulfa drugs"],
        "last_visit_days_ago": 28,
    },
    {
        "first_name": "Bo",
        "last_name": "Tanner",
        "date_of_birth": "2009-09-15",
        "phone": "512-555-0121",
        "address_line": "402 Lost Pines Rd",
        "city": "Bastrop",
        "postal_code": "78602",
        "blood_type": "B-",
        "status": "active",
        "conditions": ["Concussion (junior rodeo), resolved"],
        "medications": [],
        "allergies": [],
        "last_visit_days_ago": 110,
        "notes": [
            (
                110,
                "Follow-up after junior rodeo concussion. Symptom-free for two weeks. Cleared for a graded return to riding; helmet strongly recommended.",
            ),
        ],
    },
    {
        "first_name": "Doc",
        "last_name": "Sutherland",
        "date_of_birth": "1951-06-20",
        "phone": "432-555-0122",
        "address_line": "19 Big Bend Hwy",
        "city": "Alpine",
        "postal_code": "79830",
        "blood_type": "A+",
        "status": "active",
        "conditions": ["Hypertension"],
        "medications": ["Amlodipine 5 mg daily"],
        "allergies": ["Bee and wasp venom"],
        "last_visit_days_ago": 47,
    },
    {
        "first_name": "Ruby",
        "last_name": "Montoya",
        "date_of_birth": "1983-02-14",
        "phone": "915-555-0123",
        "address_line": "860 Franklin Mountain Dr",
        "city": "El Paso",
        "postal_code": "79901",
        "blood_type": "O+",
        "status": "active",
        "conditions": ["Gestational diabetes (2019), resolved"],
        "medications": [],
        "allergies": ["Amoxicillin"],
        "last_visit_days_ago": 201,
    },
    {
        "first_name": "Smokey",
        "last_name": "Jarrett",
        "date_of_birth": "1973-10-31",
        "phone": "361-555-0124",
        "address_line": "5 Fishing Pier Rd",
        "city": "Port Aransas",
        "postal_code": "78373",
        "blood_type": "AB+",
        "status": "inactive",
        "conditions": ["Chronic bronchitis", "Tobacco use disorder"],
        "medications": ["Albuterol inhaler as needed"],
        "allergies": [],
        "last_visit_days_ago": 455,
    },
]

# Pools for the generated patients. 10 first names x 10 last names gives 100
# unique people; see `generated_patient` in seed.py for how they are combined.
FIRST_NAMES = [
    "Buck", "Hank", "Jesse", "Wade", "Colt",
    "Reba", "Dolly", "Patsy", "Tammy", "June",
]  # fmt: skip
LAST_NAMES = [
    "Abbott", "Boone", "Crockett", "Driscoll", "Espinoza",
    "Fuentes", "Garrison", "Hutchins", "Ibarra", "Jennings",
]  # fmt: skip
TOWNS = [
    ("Austin", "78701"), ("San Antonio", "78205"), ("Fort Worth", "76102"),
    ("Galveston", "77550"), ("Corpus Christi", "78401"), ("Tyler", "75702"),
    ("Midland", "79701"), ("Del Rio", "78840"), ("Uvalde", "78801"),
    ("Brenham", "77833"), ("Shiner", "77984"),
]  # fmt: skip
CONDITIONS = [
    "Hypertension", "Type 2 diabetes", "Hyperlipidemia", "Asthma", "Osteoarthritis",
    "Hypothyroidism", "Chronic low back pain", "Gastroesophageal reflux disease",
    "Migraine", "Seasonal allergic rhinitis (cedar fever)",
]  # fmt: skip
# The usual medication for each entry in CONDITIONS, in the same order.
MEDICATIONS = [
    "Lisinopril 10 mg daily", "Metformin 500 mg twice daily", "Atorvastatin 20 mg nightly",
    "Albuterol inhaler as needed", "Acetaminophen 500 mg as needed",
    "Levothyroxine 50 mcg daily", "Ibuprofen 400 mg as needed", "Omeprazole 20 mg daily",
    "Sumatriptan 50 mg as needed", "Cetirizine 10 mg daily",
]  # fmt: skip
ALLERGIES = ["Penicillin", "Sulfa drugs", "Latex", "Shellfish", "Peanuts", "Aspirin"]
BLOOD_TYPES = ["O+", "A+", "B+", "O-", "A-", "AB+", "B-", "AB-"]
